################################################################################
# phpmemcachedadmin - apenas redundancia do repo original
################################################################################

FROM moonbuggy2000/phpmemcachedadmin:1.3.0-ppc64le