################################################################################
# openldap - apenas redundancia do repo original
################################################################################

FROM docker.io/botsudo/docker-openldap:latest