################################################################################
# Postgres Imagem Alternativa - apenas redundancia do repo oficial
################################################################################

FROM docker.io/postgres:latest