################################################################################
# Memcached Oficial - apenas redundancia do repo oficial
################################################################################

FROM docker.io/memcached:latest